import { CreateSubjectInput, UpdateSubjectInput } from '../utils/validators';
import { subjectSectionAverage, studentsWithNoteInSubject } from './aggregation.service';
import { gradesService } from './grades.service';
import * as closeCycleService from './promotion/close-cycle.service';
import { findTeacherAssignmentConflicts, ScheduleConflictError } from './schedule-conflicts.service';
import { borrarGuardandoCopia, QuienBorra } from '../utils/papelera';
import { NotFoundError } from '../utils/errors';

export class SubjectsService {
    async getAllSubjects(filters: any = {}, prisma: any) {
        const { page = 1, limit = 10, search, academicYearId, ...otherFilters } = filters;
        const skip = (page - 1) * limit;

        const where: any = {};

        if (search) {
            where.OR = [
                { name: { contains: search } },
                { code: { contains: search } }
            ];
        }

        // Build include filter for classroomSubjects based on academicYearId
        const classroomSubjectsInclude: any = {
            select: {
                teacherId: true
            }
        };

        // If academicYearId is provided, filter classroomSubjects by classroom's academicYearId
        if (academicYearId) {
            classroomSubjectsInclude.where = {
                classroom: {
                    academicYearId: academicYearId
                }
            };
        }

        const [total, subjects] = await Promise.all([
            prisma.subject.count({ where }),
            prisma.subject.findMany({
                where,
                orderBy: {
                    name: 'asc'
                },
                skip: Number(skip),
                take: Number(limit),
                include: {
                    classroomSubjects: classroomSubjectsInclude
                }
            })
        ]);

        // Calcular conteo de profesores únicos y secciones por materia
        const subjectsWithCounts = subjects.map((subject: any) => {
            const uniqueTeachers = new Set(
                subject.classroomSubjects
                    .map((cs: any) => cs.teacherId)
                    .filter((id: string | null) => id !== null)
            );

            const { classroomSubjects, ...subjectData } = subject;

            return {
                ...subjectData,
                teacherCount: uniqueTeachers.size,
                sectionCount: classroomSubjects.length // Número de secciones asignadas (filtradas por año si se especificó)
            };
        });

        return {
            items: subjectsWithCounts,
            meta: {
                total,
                page: Number(page),
                limit: Number(limit),
                totalPages: Math.ceil(total / limit)
            }
        };
    }

    async getSubjectById(
        idOrSlug: string,
        prisma: any,
        academicYearId?: string,
        periodId?: string,
        instituteId?: string
    ) {
        // CUIDs generated by Prisma match pattern: starts with 'c', 25 alphanumeric chars
        const isCuid = /^c[a-z0-9]{24}$/.test(idOrSlug);
        const whereClause = isCuid ? { id: idOrSlug } : { slug: idOrSlug };

        // 1. Resolver el ciclo escolar y sus periodos si academicYearId está disponible
        let academicYear: any = null;
        if (academicYearId) {
            academicYear = await prisma.academicYear.findUnique({
                where: { id: academicYearId },
                select: {
                    id: true,
                    name: true,
                    status: true,
                    startDate: true,
                    endDate: true,
                    periods: {
                        select: {
                            id: true,
                            name: true,
                            isActive: true,
                            startDate: true,
                            endDate: true
                        },
                        orderBy: { startDate: 'asc' }
                    }
                }
            });
        }

        // 2. Filtro por fechas del periodo/lapso si se especificó
        let periodDateFilter: any = {};
        if (periodId) {
            const period = await prisma.period.findUnique({
                where: { id: periodId },
                select: { startDate: true, endDate: true },
            });
            if (period) {
                periodDateFilter = {
                    gte: period.startDate,
                    lte: period.endDate,
                };
            }
        }

        // 3. Obtener nota mínima aprobatoria configurable del instituto
        let minPassing = 10;
        if (instituteId) {
            try {
                const config = await closeCycleService.getAcademicConfig(instituteId);
                minPassing = typeof config.notaMinimaAprobatoria === 'number' ? config.notaMinimaAprobatoria : 10;
            } catch {
                minPassing = 10;
            }
        }

        // 4. Get subject with all its assignments for the specified academic year
        const subject = await prisma.subject.findUnique({
            where: whereClause,
            include: {
                classroomSubjects: {
                    where: academicYearId ? {
                        classroom: { academicYearId }
                    } : undefined,
                    include: {
                        classroom: {
                            select: {
                                id: true,
                                name: true,
                                slug: true,
                                grade: true,
                                capacity: true,
                                academicYearId: true,
                                academicYear: {
                                    select: { name: true, status: true, startDate: true, endDate: true }
                                },
                                _count: {
                                    select: {
                                        studentClassrooms: { where: { isActive: true } }
                                    }
                                }
                            }
                        },
                        teacher: {
                            select: {
                                id: true,
                                firstName: true,
                                lastName: true,
                                email: true,
                                avatar: true
                            }
                        },
                        scheduleBlocks: {
                            select: {
                                dayOfWeek: true,
                                startTime: true,
                                endTime: true
                            }
                        }
                    }
                }
            }
        });

        if (!subject) return null;

        // Si no se pasó academicYearId directamente pero encontramos classroomSubjects, resolver academicYear
        if (!academicYear && subject.classroomSubjects.length > 0) {
            const foundYearId = subject.classroomSubjects[0]?.classroom?.academicYearId;
            if (foundYearId) {
                academicYear = await prisma.academicYear.findUnique({
                    where: { id: foundYearId },
                    select: {
                        id: true,
                        name: true,
                        status: true,
                        startDate: true,
                        endDate: true,
                        periods: {
                            select: {
                                id: true,
                                name: true,
                                isActive: true,
                                startDate: true,
                                endDate: true
                            },
                            orderBy: { startDate: 'asc' }
                        }
                    }
                });
            }
        }

        const classroomIds = subject.classroomSubjects.map((cs: any) => cs.classroom.id);

        // Pre-fetch observaciones de la materia en estas aulas
        const observationsList = await prisma.observation.findMany({
            where: {
                subjectId: subject.id,
                classroomId: { in: classroomIds },
                ...(periodDateFilter.gte ? { date: periodDateFilter } : {}),
            },
            select: { id: true, classroomId: true }
        });
        const obsMap = new Map<string, number>();
        observationsList.forEach((o: any) => {
            if (o.classroomId) {
                obsMap.set(o.classroomId, (obsMap.get(o.classroomId) || 0) + 1);
            }
        });

        // Pre-fetch asistencia de estas aulas
        const attendanceGroups = await prisma.dailyAttendance.groupBy({
            by: ['classroomId', 'status'],
            where: {
                classroomId: { in: classroomIds },
                ...(periodDateFilter.gte ? { date: periodDateFilter } : {}),
            },
            _count: { id: true }
        });
        const attMap = new Map<string, { attended: number; total: number }>();
        attendanceGroups.forEach((g: any) => {
            if (!attMap.has(g.classroomId)) {
                attMap.set(g.classroomId, { attended: 0, total: 0 });
            }
            const entry = attMap.get(g.classroomId)!;
            entry.total += g._count.id;
            if (g.status === 'PRESENT' || g.status === 'LATE') {
                entry.attended += g._count.id;
            }
        });

        // Estructuras de acumulación por Grado (1..5)
        const gradeStatsAccum: Record<number, {
            totalStudents: number;
            totalCapacity: number;
            observations: number;
            attended: number;
            attendanceTotal: number;
            studentScores: number[];
            riskCount: number;
        }> = {};

        [1, 2, 3, 4, 5].forEach(g => {
            gradeStatsAccum[g] = {
                totalStudents: 0,
                totalCapacity: 0,
                observations: 0,
                attended: 0,
                attendanceTotal: 0,
                studentScores: [],
                riskCount: 0
            };
        });

        let allSubjectScores: number[] = [];
        let totalSubjectRisk = 0;
        let totalSubjectCapacity = 0;

        // Transform data for frontend with real calculated averages and risk
        const sections = await Promise.all(
            subject.classroomSubjects.map(async (cs: any) => {
                const classroomId = cs.classroom.id;
                const gradeNum = cs.classroom.grade;
                const capacity = cs.classroom.capacity || 35;
                const studentCount = cs.classroom._count.studentClassrooms;

                totalSubjectCapacity += capacity;

                if (gradeStatsAccum[gradeNum]) {
                    gradeStatsAccum[gradeNum].totalStudents += studentCount;
                    gradeStatsAccum[gradeNum].totalCapacity += capacity;
                }

                // Observaciones de la sección
                const sectionObs = obsMap.get(classroomId) || 0;
                if (gradeStatsAccum[gradeNum]) {
                    gradeStatsAccum[gradeNum].observations += sectionObs;
                }

                // Asistencia de la sección
                const att = attMap.get(classroomId);
                let sectionAttendanceRate = 0;
                if (att && att.total > 0) {
                    sectionAttendanceRate = Math.round((att.attended / att.total) * 100);
                    if (gradeStatsAccum[gradeNum]) {
                        gradeStatsAccum[gradeNum].attended += att.attended;
                        gradeStatsAccum[gradeNum].attendanceTotal += att.total;
                    }
                }

                // Promedio ponderado y riesgo real de los alumnos
                let average = 0;
                let sectionRiskCount = 0;
                let secMin = 0;
                let secMax = 0;
                const secScores: number[] = [];

                try {
                    const withData = await studentsWithNoteInSubject(prisma, classroomId, subject.id, periodId);
                    for (const studentId of withData) {
                        const stuAvg = await gradesService.calculateWeightedSubjectAverage(
                            prisma,
                            studentId,
                            subject.id,
                            periodId
                        );
                        if (stuAvg > 0) {
                            secScores.push(stuAvg);
                            allSubjectScores.push(stuAvg);
                            if (gradeStatsAccum[gradeNum]) {
                                gradeStatsAccum[gradeNum].studentScores.push(stuAvg);
                            }
                            if (stuAvg < minPassing) {
                                sectionRiskCount++;
                                totalSubjectRisk++;
                                if (gradeStatsAccum[gradeNum]) {
                                    gradeStatsAccum[gradeNum].riskCount++;
                                }
                            }
                        }
                    }

                    if (secScores.length > 0) {
                        secMin = Math.min(...secScores);
                        secMax = Math.max(...secScores);
                        average = Math.round((secScores.reduce((a, b) => a + b, 0) / secScores.length) * 10) / 10;
                    }
                } catch {
                    // Fallback to 0 if error occurs
                }

                return {
                    id: cs.classroom.id,
                    name: cs.classroom.name,
                    slug: cs.classroom.slug,
                    grade: cs.classroom.grade,
                    capacity,
                    studentCount,
                    weeklyBlocks: cs.weeklyBlocks,
                    hoursPerWeek: cs.hoursPerWeek,
                    teacher: cs.teacher ? {
                        id: cs.teacher.id,
                        name: `${cs.teacher.firstName} ${cs.teacher.lastName}`,
                        email: cs.teacher.email,
                        avatar: cs.teacher.avatar || null
                    } : null,
                    schedule: cs.scheduleBlocks.length > 0
                        ? cs.scheduleBlocks.map((s: any) => {
                            const days = ['', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'];
                            const dayName = typeof s.dayOfWeek === 'number' ? (days[s.dayOfWeek] || `Día ${s.dayOfWeek}`) : String(s.dayOfWeek).substring(0, 3);
                            return `${dayName} ${s.startTime}`;
                        }).join(', ')
                        : 'Por definir',
                    average,
                    minAverage: secMin > 0 ? Math.round(secMin * 10) / 10 : undefined,
                    maxAverage: secMax > 0 ? Math.round(secMax * 10) / 10 : undefined,
                    riskCount: sectionRiskCount,
                    attendance: `${sectionAttendanceRate}%`,
                    observations: sectionObs
                };
            })
        );

        // Formatear gradeStats (1..5)
        const gradeStats: Record<number, any> = {};
        [1, 2, 3, 4, 5].forEach(g => {
            const accum = gradeStatsAccum[g];
            const gAvg = accum.studentScores.length > 0
                ? Math.round((accum.studentScores.reduce((a, b) => a + b, 0) / accum.studentScores.length) * 10) / 10
                : 0;
            const gMin = accum.studentScores.length > 0 ? Math.round(Math.min(...accum.studentScores) * 10) / 10 : 0;
            const gMax = accum.studentScores.length > 0 ? Math.round(Math.max(...accum.studentScores) * 10) / 10 : 0;
            const gAtt = accum.attendanceTotal > 0
                ? Math.round((accum.attended / accum.attendanceTotal) * 100)
                : 0;

            gradeStats[g] = {
                grade: g,
                stats: {
                    average: gAvg,
                    minAverage: gMin > 0 ? gMin : undefined,
                    maxAverage: gMax > 0 ? gMax : undefined,
                    riskCount: accum.riskCount,
                    occupancy: `${accum.totalStudents}/${accum.totalCapacity}`,
                    attendance: `${gAtt}%`,
                    observations: accum.observations
                }
            };
        });

        // Formatear Global Stats
        const globalAvg = allSubjectScores.length > 0
            ? Math.round((allSubjectScores.reduce((a, b) => a + b, 0) / allSubjectScores.length) * 10) / 10
            : 0;
        const globalMin = allSubjectScores.length > 0 ? Math.round(Math.min(...allSubjectScores) * 10) / 10 : 0;
        const globalMax = allSubjectScores.length > 0 ? Math.round(Math.max(...allSubjectScores) * 10) / 10 : 0;

        const totalAttended = Object.values(gradeStatsAccum).reduce((sum, g) => sum + g.attended, 0);
        const totalAttRecords = Object.values(gradeStatsAccum).reduce((sum, g) => sum + g.attendanceTotal, 0);
        const globalAttendance = totalAttRecords > 0 ? Math.round((totalAttended / totalAttRecords) * 100) : 0;

        const totalEnrolledStudents = sections.reduce((acc: number, s: any) => acc + s.studentCount, 0);

        const stats = {
            average: globalAvg,
            minAverage: globalMin > 0 ? globalMin : undefined,
            maxAverage: globalMax > 0 ? globalMax : undefined,
            riskCount: totalSubjectRisk,
            occupancy: `${totalEnrolledStudents}/${totalSubjectCapacity}`,
            attendance: `${globalAttendance}%`,
            observations: observationsList.length
        };

        // Get unique teachers with subject hours and total hours
        const teachersMap = new Map();
        subject.classroomSubjects.forEach((cs: any) => {
            const blocks = cs.weeklyBlocks || 0;
            const hours = cs.hoursPerWeek || (blocks * 45 / 60);
            if (cs.teacher && !teachersMap.has(cs.teacher.id)) {
                teachersMap.set(cs.teacher.id, {
                    id: cs.teacher.id,
                    name: `${cs.teacher.firstName} ${cs.teacher.lastName}`,
                    email: cs.teacher.email,
                    avatar: cs.teacher.avatar || null,
                    sectionsCount: 1,
                    subjectWeeklyBlocks: blocks,
                    subjectWeeklyHours: hours,
                });
            } else if (cs.teacher) {
                const existing = teachersMap.get(cs.teacher.id);
                existing.sectionsCount++;
                existing.subjectWeeklyBlocks += blocks;
                existing.subjectWeeklyHours += hours;
            }
        });

        const { classroomSubjects, ...subjectData } = subject;

        return {
            ...subjectData,
            academicYear,
            stats,
            gradeStats,
            sections,
            teachers: Array.from(teachersMap.values()),
            sectionCount: sections.length,
            teacherCount: teachersMap.size,
            totalStudents: totalEnrolledStudents
        };
    }

    async createSubject(data: CreateSubjectInput, prisma: any) {
        const { generateSlug } = await import('../utils/slug');

        return prisma.subject.create({
            data: {
                ...data,
                slug: generateSlug(data.name)
            }
        });
    }

    async updateSubject(id: string, data: UpdateSubjectInput, prisma: any) {
        return prisma.subject.update({
            where: { id },
            data
        });
    }

    /**
     * BORRAR UNA MATERIA SE LLEVA TODAS SUS NOTAS
     *
     * Esto hacía `prisma.subject.delete()` a pelo, sin pasar por la papelera. Y
     * una materia no se va sola: PostgreSQL borra en cascada sus notas, su plan
     * de evaluación, sus horarios, sus sesiones de clase y sus asignaciones a
     * secciones.
     *
     * O sea: un clic por error en «eliminar materia» borraba las notas de todos
     * los alumnos que la cursan, y no quedaba copia de nada. Lo único que había
     * era el respaldo de anoche, que al restaurarlo borra todo lo que el liceo
     * hizo hoy.
     *
     * `borrarGuardandoCopia` guarda la materia **y todo lo que la cascada
     * arrastra** antes de tocar nada. Si no cabe, no borra.
     */
    async deleteSubject(id: string, prisma: any, quien: QuienBorra = {}) {
        const borradas = await borrarGuardandoCopia(prisma, 'subject', { id }, quien);
        if (borradas === 0) {
            throw new NotFoundError('Asignatura no encontrada');
        }
        return { id };
    }

    // Obtener asignaturas filtradas por grado (buscando en las aulas de ese grado)
    async getSubjectsByGrade(grade: number, prisma: any, academicYearId?: string) {

        const classroomWhere: any = {
            grade: grade
        };

        if (academicYearId) {
            classroomWhere.academicYearId = academicYearId;
        }

        // Buscamos materias que estén asignadas a al menos un aula de ese grado
        const subjects = await prisma.subject.findMany({
            where: {
                classroomSubjects: {
                    some: {
                        classroom: classroomWhere
                    }
                }
            },
            include: {
                // Opcional: incluir detalles de asignación si es necesario, 
                // pero para "listar materias del grado" basta con la entidad Subject
            }
        });
        return subjects;
    }

    async getSubjectTeachers(subjectId: string, prisma: any) {
        // Obtener profesores asignados a esta materia en cualquier aula
        const assignments = await prisma.classroomSubject.findMany({
            where: { subjectId },
            include: {
                teacher: {
                    select: {
                        id: true,
                        firstName: true,
                        lastName: true,
                        email: true
                    }
                }
            },
            distinct: ['teacherId'] // Evitar duplicados si el mismo profe da la materia en varias secciones
        });
        return assignments.map((a: any) => a.teacher);
    }

    // Retirado: assignTeacherToSubject (versión simple) 
    // Reemplazado por: asignación a un grado entero (todas las secciones)
    async assignSubjectToGrade(grade: number, subjectId: string, teacherId: string | null, prisma: any, academicYearId?: string) {
        let yearId = academicYearId;

        if (!yearId) {
            // 1. Encontrar el AÑO ACTIVO si no se especifica
            const activeYear = await prisma.academicYear.findFirst({
                where: { status: 'ACTIVE' }
            });

            if (!activeYear) {
                throw new Error('No hay un año académico activo y no se especificó un año destino.');
            }
            yearId = activeYear.id;
        }

        // 2. Encontrar todas las aulas de ese grado en el año objetivo
        const classrooms = await prisma.classroom.findMany({
            where: {
                grade: grade,
                academicYearId: yearId
            }
        });

        if (classrooms.length === 0) {
            // Si no hay aulas, no hacemos nada (o podríamos crear el aula por defecto si fuera lógica de negocio)
            return [];
        }

        // Antes de tocar nada: si el profesor CAMBIA en secciones que ya tienen
        // bloques de esta materia, esos bloques pasarían a ocuparle. Se comprueban
        // TODAS las secciones primero para no dejar la asignación a medias.
        if (teacherId) {
            const changing = await prisma.classroomSubject.findMany({
                where: {
                    subjectId,
                    classroomId: { in: classrooms.map((c: any) => c.id) },
                    // `{ not }` deja fuera los NULL en SQL: sin profesor también "cambia"
                    OR: [{ teacherId: null }, { teacherId: { not: teacherId } }],
                },
                select: { id: true },
            });
            const clashes = await findTeacherAssignmentConflicts(
                prisma,
                changing.map((c: any) => c.id),
                teacherId
            );
            if (clashes.length > 0) {
                throw new ScheduleConflictError(clashes);
            }
        }

        // 3. Crear (o actualizar) la relación ClassroomSubject para CADA aula
        const results = [];
        for (const classroom of classrooms) {
            // Verificar si ya existe la asignación
            const existing = await prisma.classroomSubject.findUnique({
                where: {
                    classroomId_subjectId: {
                        classroomId: classroom.id,
                        subjectId: subjectId
                    }
                }
            });

            if (existing) {
                // Si ya existe, actualizamos el profesor si se proporcionó uno
                if (teacherId) {
                    const updated = await prisma.classroomSubject.update({
                        where: { id: existing.id },
                        data: { teacherId }
                    });
                    results.push(updated);
                } else {
                    results.push(existing);
                }
            } else {
                if (!teacherId) {
                    // TODO: Manejar caso de "sin profesor". Por ahora saltamos.
                    continue;
                }

                const created = await prisma.classroomSubject.create({
                    data: {
                        classroomId: classroom.id,
                        subjectId: subjectId,
                        teacherId: teacherId
                    }
                });
                results.push(created);
            }
        }
        return results;
    }

    async removeSubjectFromGrade(grade: number, subjectId: string, prisma: any, academicYearId?: string, quien: QuienBorra = {}) {
        let yearId = academicYearId;

        if (!yearId) {
            const activeYear = await prisma.academicYear.findFirst({
                where: { status: 'ACTIVE' }
            });
            if (!activeYear) return { count: 0 };
            yearId = activeYear.id;
        }

        // Con copia en la papelera: quitar la materia de un año se lleva la
        // asignación de cada sección con su profesor y su historial. Esto era
        // un `deleteMany` a pelo, uno de los dos borrados que se saltaban la regla.
        const count = await borrarGuardandoCopia(
            prisma,
            'classroomSubject',
            { subjectId, classroom: { grade, academicYearId: yearId } },
            quien
        );
        return { count };
    }

    async getSubjectStudents(subjectId: string, prisma: any) {
        // Estudiantes inscritos en aulas que tienen esta materia
        // User -> StudentClassroom -> Classroom -> ClassroomSubject (subjectId)
        // Es un poco complejo, simplificamos:
        // Buscamos ClassroomSubjects con este subjectId, obtenemos las aulas, y de ahí los alumnos.

        const classroomSubjects = await prisma.classroomSubject.findMany({
            where: { subjectId },
            include: {
                classroom: {
                    include: {
                        studentClassrooms: {
                            where: { isActive: true },
                            include: {
                                student: true
                            }
                        }
                    }
                }
            }
        });

        // Aplanar resultados
        const students = classroomSubjects.flatMap((cs: any) =>
            cs.classroom.studentClassrooms.map((sc: any) => sc.student)
        );

        // Eliminar duplicados por ID
        return Array.from(new Map(students.map((s: any) => [s.id, s])).values());
    }

    async getSubjectStats(prisma: any) {
        return prisma.subject.aggregate({
            _count: {
                id: true
            }
        });
    }
}
