import { CreateSubjectInput, UpdateSubjectInput } from '../utils/validators';

export class SubjectsService {
    async getAllSubjects(filters: any = {}, prisma: any) {
        const { page = 1, limit = 10, search, academicYearId, ...otherFilters } = filters;
        const skip = (page - 1) * limit;

        const where: any = {};

        if (search) {
            where.OR = [
                { name: { contains: search } },
                { code: { contains: search } }
            ];
        }

        // Build include filter for classroomSubjects based on academicYearId
        const classroomSubjectsInclude: any = {
            select: {
                teacherId: true
            }
        };

        // If academicYearId is provided, filter classroomSubjects by classroom's academicYearId
        if (academicYearId) {
            classroomSubjectsInclude.where = {
                classroom: {
                    academicYearId: academicYearId
                }
            };
        }

        const [total, subjects] = await Promise.all([
            prisma.subject.count({ where }),
            prisma.subject.findMany({
                where,
                orderBy: {
                    name: 'asc'
                },
                skip: Number(skip),
                take: Number(limit),
                include: {
                    classroomSubjects: classroomSubjectsInclude
                }
            })
        ]);

        // Calcular conteo de profesores únicos y secciones por materia
        const subjectsWithCounts = subjects.map((subject: any) => {
            const uniqueTeachers = new Set(
                subject.classroomSubjects
                    .map((cs: any) => cs.teacherId)
                    .filter((id: string | null) => id !== null)
            );

            const { classroomSubjects, ...subjectData } = subject;

            return {
                ...subjectData,
                teacherCount: uniqueTeachers.size,
                sectionCount: classroomSubjects.length // Número de secciones asignadas (filtradas por año si se especificó)
            };
        });

        return {
            items: subjectsWithCounts,
            meta: {
                total,
                page: Number(page),
                limit: Number(limit),
                totalPages: Math.ceil(total / limit)
            }
        };
    }

    async getSubjectById(idOrSlug: string, prisma: any, academicYearId?: string) {
        // CUIDs generated by Prisma match pattern: starts with 'c', 25 alphanumeric chars
        const isCuid = /^c[a-z0-9]{24}$/.test(idOrSlug);
        const whereClause = isCuid ? { id: idOrSlug } : { slug: idOrSlug };

        // Get subject with all its assignments
        const subject = await prisma.subject.findUnique({
            where: whereClause,
            include: {
                classroomSubjects: {
                    where: academicYearId ? {
                        classroom: { academicYearId }
                    } : undefined,
                    include: {
                        classroom: {
                            select: {
                                id: true,
                                name: true,
                                slug: true,
                                grade: true,
                                academicYearId: true,
                                academicYear: {
                                    select: { name: true }
                                },
                                _count: {
                                    select: { studentClassrooms: true }
                                }
                            }
                        },
                        teacher: {
                            select: {
                                id: true,
                                firstName: true,
                                lastName: true,
                                email: true
                            }
                        },
                        scheduleBlocks: {
                            select: {
                                dayOfWeek: true,
                                startTime: true,
                                endTime: true
                            }
                        }
                    }
                }
            }
        });

        if (!subject) return null;

        // Transform data for frontend
        const sections = subject.classroomSubjects.map((cs: any) => ({
            id: cs.classroom.id,
            name: cs.classroom.name,
            slug: cs.classroom.slug,
            grade: cs.classroom.grade,
            studentCount: cs.classroom._count.studentClassrooms,
            weeklyBlocks: cs.weeklyBlocks,
            hoursPerWeek: cs.hoursPerWeek,
            teacher: cs.teacher ? {
                id: cs.teacher.id,
                name: `${cs.teacher.firstName} ${cs.teacher.lastName}`,
                email: cs.teacher.email,
                avatar: cs.teacher.avatar || null
            } : null,
            schedule: cs.scheduleBlocks.length > 0
                ? cs.scheduleBlocks.map((s: any) => `${s.dayOfWeek.substring(0, 3)} ${s.startTime}`).join(', ')
                : 'Por definir',
            average: 0 // TODO: Calculate from grades
        }));

        // Get unique teachers
        const teachersMap = new Map();
        subject.classroomSubjects.forEach((cs: any) => {
            if (cs.teacher && !teachersMap.has(cs.teacher.id)) {
                teachersMap.set(cs.teacher.id, {
                    id: cs.teacher.id,
                    name: `${cs.teacher.firstName} ${cs.teacher.lastName}`,
                    email: cs.teacher.email,
                    avatar: cs.teacher.avatar || null,
                    sectionsCount: 1
                });
            } else if (cs.teacher) {
                teachersMap.get(cs.teacher.id).sectionsCount++;
            }
        });

        const { classroomSubjects, ...subjectData } = subject;

        return {
            ...subjectData,
            sections,
            teachers: Array.from(teachersMap.values()),
            sectionCount: sections.length,
            teacherCount: teachersMap.size,
            totalStudents: sections.reduce((acc: number, s: any) => acc + s.studentCount, 0)
        };
    }

    async createSubject(data: CreateSubjectInput, prisma: any) {
        const { generateSlug } = await import('../utils/slug');

        return prisma.subject.create({
            data: {
                ...data,
                slug: generateSlug(data.name)
            }
        });
    }

    async updateSubject(id: string, data: UpdateSubjectInput, prisma: any) {
        return prisma.subject.update({
            where: { id },
            data
        });
    }

    async deleteSubject(id: string, prisma: any) {
        return prisma.subject.delete({
            where: { id }
        });
    }

    // Obtener asignaturas filtradas por grado (buscando en las aulas de ese grado)
    async getSubjectsByGrade(grade: number, prisma: any, academicYearId?: string) {

        const classroomWhere: any = {
            grade: grade
        };

        if (academicYearId) {
            classroomWhere.academicYearId = academicYearId;
        }

        // Buscamos materias que estén asignadas a al menos un aula de ese grado
        const subjects = await prisma.subject.findMany({
            where: {
                classroomSubjects: {
                    some: {
                        classroom: classroomWhere
                    }
                }
            },
            include: {
                // Opcional: incluir detalles de asignación si es necesario, 
                // pero para "listar materias del grado" basta con la entidad Subject
            }
        });
        return subjects;
    }

    async getSubjectTeachers(subjectId: string, prisma: any) {
        // Obtener profesores asignados a esta materia en cualquier aula
        const assignments = await prisma.classroomSubject.findMany({
            where: { subjectId },
            include: {
                teacher: {
                    select: {
                        id: true,
                        firstName: true,
                        lastName: true,
                        email: true
                    }
                }
            },
            distinct: ['teacherId'] // Evitar duplicados si el mismo profe da la materia en varias secciones
        });
        return assignments.map((a: any) => a.teacher);
    }

    // Retirado: assignTeacherToSubject (versión simple) 
    // Reemplazado por: asignación a un grado entero (todas las secciones)
    async assignSubjectToGrade(grade: number, subjectId: string, teacherId: string | null, prisma: any, academicYearId?: string) {
        let yearId = academicYearId;

        if (!yearId) {
            // 1. Encontrar el AÑO ACTIVO si no se especifica
            const activeYear = await prisma.academicYear.findFirst({
                where: { status: 'ACTIVE' }
            });

            if (!activeYear) {
                throw new Error('No hay un año académico activo y no se especificó un año destino.');
            }
            yearId = activeYear.id;
        }

        // 2. Encontrar todas las aulas de ese grado en el año objetivo
        const classrooms = await prisma.classroom.findMany({
            where: {
                grade: grade,
                academicYearId: yearId
            }
        });

        if (classrooms.length === 0) {
            // Si no hay aulas, no hacemos nada (o podríamos crear el aula por defecto si fuera lógica de negocio)
            return [];
        }

        // 3. Crear (o actualizar) la relación ClassroomSubject para CADA aula
        const results = [];
        for (const classroom of classrooms) {
            // Verificar si ya existe la asignación
            const existing = await prisma.classroomSubject.findUnique({
                where: {
                    classroomId_subjectId: {
                        classroomId: classroom.id,
                        subjectId: subjectId
                    }
                }
            });

            if (existing) {
                // Si ya existe, actualizamos el profesor si se proporcionó uno
                if (teacherId) {
                    const updated = await prisma.classroomSubject.update({
                        where: { id: existing.id },
                        data: { teacherId }
                    });
                    results.push(updated);
                } else {
                    results.push(existing);
                }
            } else {
                if (!teacherId) {
                    // TODO: Manejar caso de "sin profesor". Por ahora saltamos.
                    continue;
                }

                const created = await prisma.classroomSubject.create({
                    data: {
                        classroomId: classroom.id,
                        subjectId: subjectId,
                        teacherId: teacherId
                    }
                });
                results.push(created);
            }
        }
        return results;
    }

    async removeSubjectFromGrade(grade: number, subjectId: string, prisma: any, academicYearId?: string) {
        let yearId = academicYearId;

        if (!yearId) {
            const activeYear = await prisma.academicYear.findFirst({
                where: { status: 'ACTIVE' }
            });
            if (!activeYear) return { count: 0 };
            yearId = activeYear.id;
        }

        return prisma.classroomSubject.deleteMany({
            where: {
                subjectId: subjectId,
                classroom: {
                    grade: grade,
                    academicYearId: yearId
                }
            }
        });
    }

    async getSubjectStudents(subjectId: string, prisma: any) {
        // Estudiantes inscritos en aulas que tienen esta materia
        // User -> StudentClassroom -> Classroom -> ClassroomSubject (subjectId)
        // Es un poco complejo, simplificamos:
        // Buscamos ClassroomSubjects con este subjectId, obtenemos las aulas, y de ahí los alumnos.

        const classroomSubjects = await prisma.classroomSubject.findMany({
            where: { subjectId },
            include: {
                classroom: {
                    include: {
                        studentClassrooms: {
                            where: { isActive: true },
                            include: {
                                student: true
                            }
                        }
                    }
                }
            }
        });

        // Aplanar resultados
        const students = classroomSubjects.flatMap((cs: any) =>
            cs.classroom.studentClassrooms.map((sc: any) => sc.student)
        );

        // Eliminar duplicados por ID
        return Array.from(new Map(students.map((s: any) => [s.id, s])).values());
    }

    async getSubjectStats(prisma: any) {
        return prisma.subject.aggregate({
            _count: {
                id: true
            }
        });
    }
}
